export async function load({ url }) {
	// Iimplement calling the Bun File API.

	return {
		hola: 'ohola',
		content:
			'<p>Hola! soy <a href="https://www.vicentematus.cl/" rel="nofollow" data-svelte-h="svelte-1qcfrly">Vicente Matus</a>. Estás viendo mis notas.</p> <p><a href="https://notes.andymatuschak.org/z5E5QawiXCMbtNtupvxeoEX" rel="nofollow" data-svelte-h="svelte-thgqih">Estas notas principalmente son escritas para mí:</a> son una forma de expresar mi estudio o pensamientos de distintos temas. Está en progreso por lo que hay notas incompletas. Las estoy haciendo públicas ya que necesitaba poder expresar mis ideas al internet.</p> <p data-svelte-h="svelte-1ofna4j">Puedes ver lo último que estoy estudiando/ensayos:</p> <ul><li>Te recomiendo empezar por este: <a href="varios/cambios-internos/Como%20cambi%C3%A9%20de%20doomer%20a%20bloomer.md" data-svelte-h="svelte-6icam">Como cambié de doomer a bloomer</a></li> <li><a href="varios/cambios-internos/Default%20de%20las%20personas.md" data-svelte-h="svelte-113gnkl">Default de las personas</a></li> <li><a href="ideas/Elige%20tus%20batallas.md" data-svelte-h="svelte-1itsddq">Elige tus batallas</a></li> <li><a href="varios/conocimiento/Shallow%20vs%20Deep%20Knowledge.md" data-svelte-h="svelte-1wof3iz">Shallow vs Deep Knowledge</a></li> <li><a href="ideas/El%20pensamiento%20no%20es%20unilateral.md" data-svelte-h="svelte-wbspu4">El pensamiento no es unilateral</a></li> <li><a href="varios/Cosas%20que%20desconozco.md" data-svelte-h="svelte-f2ndss">Cosas que desconozco</a></li> <li><a href="varios/cambios-internos/Despu%C3%A9s%20del%20miedo%20esta%20la%20recompensa.md" data-svelte-h="svelte-flk29y">Después del miedo esta la recompensa</a></li> <li><a href="videos/dwarkesh-patel-interviews/Patrick%20Collison%20(Stripe%20CEO)%20-%20Craft,%20Beauty,%20&%20The%20Future%20of%20Payments.md" data-svelte-h="svelte-162lust">Patrick Collison (Stripe CEO) - Craft, Beauty, &amp; The Future of Payments</a></li> <li><a href="Libros/Steve%20Job%20-%20Walter%20Isaacson.md" data-svelte-h="svelte-1tforqz">Steve Job - Walter Isaacson</a></li> <li><a href="Libros/Clean%20Architectura%20Notas.md" data-svelte-h="svelte-1ww9cfz">Clean Architectura Notas</a></li> <li><a href="Libros/On%20Writing%20Well%20-%20William%20Zinsser.md" data-svelte-h="svelte-u7kt6s">On Writing Well - William Zinsser</a></li> <li><a href="varios/comunicacion/Hacer%20valer%20tu%20trabajo.md" data-svelte-h="svelte-1vq4xee">Hacer valer tu trabajo</a></li> <li><a href="videos/Si%20estas%20bloqueado,%20pregunta!.md" data-svelte-h="svelte-1xz5s4j">Si estas bloqueado, pregunta!</a></li></ul> <p><a href="https://andymatuschak.org/" rel="nofollow" data-svelte-h="svelte-e0dihl">Inspirado por el trabajo de Andy Matuschak</a>. El consejo que me dió cuando le pregunté si debía empezar a tomar notas por email: ”<em data-svelte-h="svelte-1ehqjr4">Just get started!” is very powerful here!</em>”.  También gracias a <a href="https://github.com/agucova" rel="nofollow" data-svelte-h="svelte-k9fpam">@agucova</a> por mostrarme su trabajo.</p'
	};
}
